version: '2'
services:
    node:
        build: .
        command: node /myapp/app.js
        volumes:
            - /Users/nagaiyouta/work/docker/node/myapp/:/myapp
        ports:
            - 3000:3000
        depends_on:
            - db
        restart: always
    db:
        image: mariadb
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: node
        restart: always
